#!/usr/bin/env python3

import sys

def main():
  # command = input("ccwc ")
  option = sys.argv[1]
  file_name = sys.argv[2]

  try:
    with open(file_name, "rb") as file:
      content = file.read()

      if option == "-c":
        print(f"{len(content)} {file_name}")

  except FileNotFoundError:
    print(f"Error: {file_name} was not found")

if __name__ == "__main__":
  main()