#!/usr/bin/env python3

import sys

def main():
  try:
    option = sys.argv[1]
    file_name = sys.argv[2]

  except IndexError:
    print("Command error\nUsage: ./ccwc -<command options> <filename>")
    sys.exit(1)

  try:
    with open(file_name, "rb") as file:
      if option == "-c":
        byte_count = 0
        
        while chunk := file.read(4096):
          byte_count += len(chunk)

        print(f"  {byte_count} {file_name}")
      else :
        print(f"{option} command not found")
        sys.exit(1)

  except FileNotFoundError:
    print(f"Error: {file_name} was not found")
    sys.exit(1)

if __name__ == "__main__":
  main()