#!/usr/bin/env python3

import sys

WHITESPACE = {
  ord(" "),
  ord("\t"),
  ord("\n"),
  ord("\r"),
  ord("\v"),
  ord("\f")
}

def main():
  try:
    option = sys.argv[1]
    file_name = sys.argv[2]

  except IndexError:
    print("Command error\nUsage: ./ccwc -<command options> <filename>")
    sys.exit(1)

  try:
    with open(file_name, "rb") as file:
      if option == "-c":
        byte_count = 0
        
        while chunk := file.read(4096):
          byte_count += len(chunk)

        print(f"  {byte_count} {file_name}")
      elif option == "-l":
        line_count = 0

        while chunk := file.read(4096):
          line_count += chunk.count(b"\n")

        print(f"    {line_count} {file_name}")
      elif option == "-w":
        word_count = 0
        chunk_temp = b""
        # in_word = False

        while chunk := file.read(4096):
          # Best case for python using split() instead of Byte-by-Byte
          word_count += len(chunk.split()) 

          if chunk_temp:
            if (chunk_temp[-1] not in WHITESPACE) and (chunk[0] not in WHITESPACE):
              word_count -= 1

          # Based on state machine
          # for b in chunk:
          #   if b not in WHITESPACE:
          #     if not in_word:
          #       word_count += 1
          #       in_word = True
          #   else:
          #     in_word = False

          chunk_temp = chunk

        print(f"   {word_count} {file_name}")
      else :
        print(f"{option} command not found")
        sys.exit(1)

  except FileNotFoundError:
    print(f"Error: {file_name} was not found")
    sys.exit(1)

if __name__ == "__main__":
  main()